---

- name: run the playbook tasks on the localhost
  hosts: all
  vars:
    elastic_version: 6.2.1
  connection: local
  become: yes
  tasks:

  - name: install the latest version of docker
    yum:
      name: docker
      state: latest

  - easy_install:
      name: pip
      state: latest

  - name: install certain python modules for docker
    pip:
      name: {{ item }}
      state: present
      with_items:
        - docker_py
        - docker-compose

  - service:
      name: docker
      enabled: yes
      state: started

  - name: pull appropriate elasticsearch images
    shell: |
      docker pull {{ item }}:{{ elastic_version }}
    with_items:
      - docker.elastic.co/elasticsearch/elasticsearch
      - docker.elastic.co/kibana/kibana
      - docker.elastic.co/beats/metricbeat






